apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      run: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        run: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.image }}
        ports:
        - containerPort: {{ .Values.app.port }}
        resources:
          limits:
            cpu: {{ .Values.app.cpu.limits }}
          requests:
            cpu: {{ .Values.app.cpu.requests }}
      priorityClassName: system-node-critical