app:
  name: node-js
  image: node
  port: 3000
  cpu:
    limits: 500m
    requests: 100m
  replicas: 10
  scale:
    cpuUtilization: 50  
    memoryUtilization: 60
  podDisruption:
    minReplica: 7

service:
  port: 80
  targetPort: 3000
  type: LoadBalancer
  lbtype: classic